In [5]:
import pandas as pd

df = pd.read_csv('Sample_File.csv')

df['date'] = pd.date_range('2026-01-01', periods=len(df))

df['date'] = pd.to_datetime(df['date'])

df = df.set_index('date')

df

             Name  Age       City
date
2026-01-01  Rahul   20      Surat
2026-01-02  Priya   21  Ahmedabad
2026-01-03   Amit   22   Vadodara
2026-01-04   Neha   20     Rajkot
2026-01-05  Kiran   23      Surat

In [6]:
df.reset_index(inplace=True)

In [ ]:
df = pd.read_csv('Sample_File.csv',index_col=['date'])

In [7]:
df.head()

        date   Name  Age       City
0 2026-01-01  Rahul   20      Surat
1 2026-01-02  Priya   21  Ahmedabad
2 2026-01-03   Amit   22   Vadodara
3 2026-01-04   Neha   20     Rajkot
4 2026-01-05  Kiran   23      Surat

In [ ]:
df.reset_index(inplace=True)

In [ ]:
df.set_index(['date','statezip'],innplace=True

In [8]:
df.head()

        date   Name  Age       City
0 2026-01-01  Rahul   20      Surat
1 2026-01-02  Priya   21  Ahmedabad
2 2026-01-03   Amit   22   Vadodara
3 2026-01-04   Neha   20     Rajkot
4 2026-01-05  Kiran   23      Surat