- pd.read_csv : csv
- pd.to_csv : csv
- np.genfromtxt : csv
- np.loadfromtxt : csv
- np.save : npy
- np.load : npy

# Let's cover the following methods in pandas
1. Writing json
2. Reading json
3. Writing excel
4. Reading excel
5. Writing gzip files
6. Reading gzip files

In [13]:
import os
os.getcwd()

'/drive/notebooks'

In [14]:
os.listdir()

['Intro.ipynb',
 'Sample_File.csv',
 'Sample_File.csv.ipynb',
 'Untitled.ipynb',
 'praactical3.ipynb',
 'practical1.ipynb',
 'practical2.ipynb',
 'practical4.ipynb',
 'practical5.ipynb',
 'practical6.ipynb',
 'practical7.ipynb',
 'practicals.ipynb',
 'untitled.py',
 'untitled1.py',
 'sqlite.ipynb',
 'cpp-tiny-ray-tracer.ipynb',
 'Lorenz.ipynb',
 'cpp.ipynb',
 'r.ipynb',
 'cpp-third-party-libs.ipynb']

In [15]:
import pandas as pd

df = pd.read_csv('Sample_File.csv')
df.head()

    Name  Age       City
0  Rahul   20      Surat
1  Priya   21  Ahmedabad
2   Amit   22   Vadodara
3   Neha   20     Rajkot
4  Kiran   23      Surat

In [16]:
df.to_json('Sample_File_json.json')

In [17]:
df = pd.read_json('Sample_File_json.json')

In [18]:
df

    Name  Age       City
0  Rahul   20      Surat
1  Priya   21  Ahmedabad
2   Amit   22   Vadodara
3   Neha   20     Rajkot
4  Kiran   23      Surat

In [ ]:
df.to_excel('Sample_File_Excel.xls', index=False)

In [ ]:
df = df.read_excel('SampleExcelFile.xls')

In [22]:
df

    Name  Age       City
0  Rahul   20      Surat
1  Priya   21  Ahmedabad
2   Amit   22   Vadodara
3   Neha   20     Rajkot
4  Kiran   23      Surat

In [ ]:
df.to_csv('SampleFilegzip.gz',compression='gzip',index = False)

In [ ]:
df = pd.read_csv('SampleFilegzip.gz')

In [24]:
df

    Name  Age       City
0  Rahul   20      Surat
1  Priya   21  Ahmedabad
2   Amit   22   Vadodara
3   Neha   20     Rajkot
4  Kiran   23      Surat